version: '3.8'

services:
  geo_rag_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo_rag_bot
    restart: unless-stopped
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./:/app/
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - geo_rag_network

networks:
  geo_rag_network:
    driver: bridge